"""Render docs/data-catalogue.md from the pinned manifests. Read-only on every manifest.

Usage: python -m scripts.data_catalogue [--output docs/data-catalogue.md]
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = """# Data catalogue

Generated by `python -m scripts.data_catalogue` from the pinned manifests. Do not edit by hand;
edit the manifest through the documented acquisition process and regenerate.

**How to fetch.** All open sources are downloaded by
`uv run --offline --locked --cache-dir .uv-cache python -m enagis acquire --skip-licensing`
(network needed once). Each file is checked against its SHA-256 before use. Restricted sources
are never redistributed. Raw files are ignored by Git (`data/raw/`), and outputs are rebuilt
offline. Licence meanings are in [LICENSE-DATA.md](../LICENSE-DATA.md) and
[data/licence-audit.md](data/licence-audit.md).
"""


def rows(manifest_path):
    manifest = json.loads((ROOT / manifest_path).read_text(encoding="utf-8"))
    for source in manifest["sources"]:
        snap = source["snapshot"]
        yield (
            source.get("dataset_name") or snap["snapshot_id"],
            snap["publisher"],
            snap["effective_on"],
            snap["retrieved_on"],
            snap["licence"],
            snap["redistribution"],
            snap["sha256"],
            snap["original_url"],
            snap.get("processing_step", ""),
            source.get("role", ""),
        )


def table(manifest_path):
    lines = [
        "| Dataset | Publisher | Source date | Retrieved | Licence | Redistributable | Role |",
        "|---|---|---|---|---|---|---|",
    ]
    detail = []
    for name, publisher, date, got, licence, redist, sha, url, step, role in rows(manifest_path):
        lines.append(
            f"| {name} | {publisher} | {date} | {got} | {licence} | "
            f"{'yes' if redist == 'permitted' else '**no (restricted)**'} | {role} |"
        )
        detail.append(f"- **{name}** — <{url}>  \n  SHA-256 `{sha}`  \n  Processing: {step}")
    return (
        "\n".join(lines)
        + "\n\n<details><summary>URLs, hashes and processing</summary>\n\n"
        + ("\n".join(detail) + "\n\n</details>\n")
    )


def interface():
    manifest = json.loads((ROOT / "web/assets/manifest.json").read_text(encoding="utf-8"))
    lines = [
        "| File | Licence | SHA-256 | URL |",
        "|---|---|---|---|",
    ]
    for source in manifest["sources"]:
        licence = (
            "Public domain (Natural Earth)" if source["path"].startswith("ne_") else "SIL OFL 1.1"
        )
        lines.append(
            f"| {source['path']} | {licence} | `{source['sha256'][:16]}…` | <{source['url']}> |"
        )
    return (
        "\n".join(lines)
        + f"\n\nRetrieved {manifest['retrieved_on']}; purpose `{manifest['purpose']}`. "
        "These files are display context only and never analysis inputs.\n"
    )


def render():
    return (
        HEADER
        + "\n## Phase 2 data spine (`docs/data/manifest.json`)\n\n"
        + table("docs/data/manifest.json")
        + "\n## Phase 4 siting covariates (`docs/data/phase4-manifest.json`)\n\n"
        + table("docs/data/phase4-manifest.json")
        + "\n## Interface display assets (`web/assets/manifest.json`)\n\n"
        + interface()
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "docs/data-catalogue.md")
    args = parser.parse_args()
    args.output.write_text(render(), encoding="utf-8", newline="\n")
    print(args.output)


if __name__ == "__main__":
    main()
